name: Pipeline CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:

 lint:
    name: Rodando Black e Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Instalar dependências
        run: |
          pip install black flake8
      - name: Rodando Black
        id: black_check
        run: |
          black --check .
      - name: Aviso de formatação black
        if: steps.black_check.outcome == 'failure'
        run: echo "Rode 'black .' no seu terminal antes de subir o código."
      - name: Rodando flake8
        run: |
          flake8 .


  build:
    name: Validação Python
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
      - name: Validar estrutura
        run: |
          echo "Estrutura validada com sucesso"

          
  ai_review:
    name: Code Review Inteligente (Git Diff)
    runs-on: ubuntu-latest
    needs: [lint, build]
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Instalar dependências da API
        run: |
          pip install google-genai requests

      - name: Executar Revisão de Código
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/ai_reviewer.py